### PR TITLE
Switch to using the setup/pants.sh.

### PR DESCRIPTION
**Pull request by jsirois**
I started on a gradlew-like self-contained bootsrap script here a while
back: http://pantsbuild.github.io/setup/

This converts to using that.

### CODE REVIEW

**Comment by jsirois** [comment]
This has problems on OSX.  More work and testing is needed on the setup repo before a switch can be made.

**Comment by viktortnk** [comment]
@jsirois `mv -T` is not supported on OSX. Same for `-p` in `mktemp`

```
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix 
```

**Comment by viktortnk** [comment]
@jsirois Got it working locally without using `-T in`mv` and changing mktemp expression to:

```
function tempdir {
  mktemp -d "$1"/pants.XXXXXX
}
```

Do you have any better workarounds?

**Comment by jsirois** [comment]
Nothing better yet.  I'll try polishing off the setup and getting a linux + OSX ci setup for it this weekend to ensure it works on both platforms and handles plugins.  Thanks for documenting the workarounds you found - I very likely will steal them.

**Pull request closed without merging**
